### ISSUE TITLE
Update permissions based on user role and "flag"

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-server#19]
please update permissions as follows

# private

- [x] items with `private` = `true` should only be visible to and editable by 
   - [x] admin users 
   - [x] manager users that created the item
- [x] ~~further only "admin" users and item creators (i.e. managers) should be able to mark items as non-private~~ _this is obsolete_

this applies to all tables with `private` field, i.e.

- [x] actors
- [x] categories
- [x] measures
- [x] pages
- [x] resources
- [x] indicators (see #20)

# is_archive 

- [x] items with `is_archive` = `true` should only be visible to and editable by users with the "admin" role and not visible to all other users
- [x] further only "admin" users should be able to make changes to the `is_archive` field (i.e. archive and un-archive items)

this applies to all tables with `is_archive` field (see #18), i.e.

- [x] actors
- [x] categories
- [x] measures
- [x] resources
- [x] indicators

(not required for "pages" table)

**Comment by tmfrnz** [comment]
@parndt please note that we updated the rules for "is_private"

**Comment by parndt** [comment]
@tmfrnz thanks 😄
