### ISSUE TITLE
Track updates to relationships in all related tables

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-server#46]
I.e. by adding a new field 'relationship_updated_at' to all principal tables (see below) that is updated with the current date anytime a change happens to a relationship (create/update/delete)

Specifically the principal tables are (with join tables nested)

- actors
  - actor_categories 
  - actor_measures
  - measure_actors
  - memberships
  - user_actors
- measures
  - actor_measures
  - measure_actors
  - measure_categories
  - measure_indicators
  - measure_measures
  - measure_resources
  - user_measures
- indicators
  - measure_indicators
- users
  - user_roles
  - user_categories (not currently used but might as well include this)
  - user_measures? (to be confirmed)
  - user_actors? (to be confirmed)

**Comment by tmfrnz** [comment]
related to https://github.com/dumparkltd/advocacy-tracker-server/issues/48#issuecomment-1198055866

**Comment by parndt** [comment]
Fixed by #53

**Comment by tmfrnz** [comment]
will still need to add new field to serializers

**Comment by tmfrnz** [comment]
@parndt could we also please track corresponding user id, i.e. `relationship_updated_by` - thanks
