### ISSUE TITLE
allow "managers" and "coordinators" to delete content they created

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-server#68]
Users with the roles "manager" or "coordinator" (see #67) should be allowed to delete content they created.

Currently deleting is limited to users with role "admin"

**Comment by parndt** [comment]
@tmfrnz currently managers are also allowed to delete with the same rights as admin - is this a bug?

**Comment by tmfrnz** [comment]
@parndt actually please ignore my previous comment. Having checked my notes, I can confirm that "deleting" should be limited to "admin" users - "managers" and "coordinators" should only be able to delete their own content

**Comment by parndt** [comment]
Ready for review, finally, @tmfrnz #71 - I'll handle squash merging it when you're happy with it.
